# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 01:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AndReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TakenCourse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(default='', max_length=100)),
                ('review', models.TextField(default='')),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='children',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='takencourse',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentsTaken', to='backend.Course'),
        ),
        migrations.AddField(
            model_name='takencourse',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='takenCourses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orreq',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orReqs', to='backend.Course'),
        ),
        migrations.AddField(
            model_name='orreq',
            name='reqCourses',
            field=models.ManyToManyField(related_name='orChildren', to='backend.Course'),
        ),
        migrations.AddField(
            model_name='andreq',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='andReqs', to='backend.Course'),
        ),
        migrations.AddField(
            model_name='andreq',
            name='reqCourses',
            field=models.ManyToManyField(related_name='andChildren', to='backend.Course'),
        ),
    ]
