# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20170817_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='andreq',
            name='course',
        ),
        migrations.RemoveField(
            model_name='andreq',
            name='reqCourses',
        ),
        migrations.AddField(
            model_name='course',
            name='reqCourses',
            field=models.ManyToManyField(related_name='andChildren', to='backend.Course'),
        ),
        migrations.DeleteModel(
            name='AndReq',
        ),
    ]
